version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    working_directory: ~/repo
    steps:
      - run: pwd
      - checkout # check out the code in the project directory
      - run: git rev-parse HEAD
      - run: git rev-parse --short HEAD
      - run: ls
      - run: echo "hello world" # run the `echo` command
      - run: pwd
